# Generated by Django 5.2.8 on 2025-12-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashadmin', '0008_benevole_pays_benevole_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='team/')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='partenariat',
            options={'ordering': ['-date_soumission'], 'verbose_name': 'Partenariat', 'verbose_name_plural': 'Partenariat'},
        ),
    ]
